/*
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BaselineOrigin
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-07T18:50:05.195+01:00")
public class BaselineOrigin {
  @SerializedName("project")
  private Integer project = null;

  @SerializedName("item")
  private Integer item = null;

  @SerializedName("filter")
  private Integer filter = null;

  @SerializedName("release")
  private Integer release = null;

  public BaselineOrigin project(Integer project) {
    this.project = project;
    return this;
  }

   /**
   * ID of a user
   * @return project
  **/
  @ApiModelProperty(value = "ID of a user")
  public Integer getProject() {
    return project;
  }

  public void setProject(Integer project) {
    this.project = project;
  }

  public BaselineOrigin item(Integer item) {
    this.item = item;
    return this;
  }

   /**
   * ID of an item
   * @return item
  **/
  @ApiModelProperty(value = "ID of an item")
  public Integer getItem() {
    return item;
  }

  public void setItem(Integer item) {
    this.item = item;
  }

  public BaselineOrigin filter(Integer filter) {
    this.filter = filter;
    return this;
  }

   /**
   * ID of a filter
   * @return filter
  **/
  @ApiModelProperty(value = "ID of a filter")
  public Integer getFilter() {
    return filter;
  }

  public void setFilter(Integer filter) {
    this.filter = filter;
  }

  public BaselineOrigin release(Integer release) {
    this.release = release;
    return this;
  }

   /**
   * ID of a release
   * @return release
  **/
  @ApiModelProperty(value = "ID of a release")
  public Integer getRelease() {
    return release;
  }

  public void setRelease(Integer release) {
    this.release = release;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaselineOrigin baselineOrigin = (BaselineOrigin) o;
    return Objects.equals(this.project, baselineOrigin.project) &&
        Objects.equals(this.item, baselineOrigin.item) &&
        Objects.equals(this.filter, baselineOrigin.filter) &&
        Objects.equals(this.release, baselineOrigin.release);
  }

  @Override
  public int hashCode() {
    return Objects.hash(project, item, filter, release);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaselineOrigin {\n");
    
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

