/*
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CommentBody;
import io.swagger.client.model.CommentLocation;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Comment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-07T18:50:05.195+01:00")
public class Comment {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("inReplyTo")
  private Integer inReplyTo = null;

  @SerializedName("createdDate")
  private OffsetDateTime createdDate = null;

  @SerializedName("createdBy")
  private Integer createdBy = null;

  @SerializedName("modifiedBy")
  private Integer modifiedBy = null;

  @SerializedName("deleted")
  private Boolean deleted = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    OPEN("OPEN"),
    
    CANCELLED("CANCELLED"),
    
    COMPLETED("COMPLETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("body")
  private CommentBody body = null;

  /**
   * Gets or Sets commentType
   */
  @JsonAdapter(CommentTypeEnum.Adapter.class)
  public enum CommentTypeEnum {
    GENERAL("GENERAL"),
    
    QUESTION("QUESTION"),
    
    PROPOSED_CHANGE("PROPOSED_CHANGE"),
    
    ACCEPTED_COMMENT("ACCEPTED_COMMENT"),
    
    REJECTED_COMMENT("REJECTED_COMMENT"),
    
    ISSUE("ISSUE"),
    
    DECISION("DECISION"),
    
    DECISION_REQUEST("DECISION_REQUEST");

    private String value;

    CommentTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CommentTypeEnum fromValue(String text) {
      for (CommentTypeEnum b : CommentTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CommentTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CommentTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CommentTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CommentTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("commentType")
  private CommentTypeEnum commentType = null;

  @SerializedName("location")
  private CommentLocation location = null;

  public Comment id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Comment inReplyTo(Integer inReplyTo) {
    this.inReplyTo = inReplyTo;
    return this;
  }

   /**
   * ID of a comment
   * @return inReplyTo
  **/
  @ApiModelProperty(required = true, value = "ID of a comment")
  public Integer getInReplyTo() {
    return inReplyTo;
  }

  public void setInReplyTo(Integer inReplyTo) {
    this.inReplyTo = inReplyTo;
  }

  public Comment createdDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }

  public Comment createdBy(Integer createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * ID of a user
   * @return createdBy
  **/
  @ApiModelProperty(required = true, value = "ID of a user")
  public Integer getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(Integer createdBy) {
    this.createdBy = createdBy;
  }

  public Comment modifiedBy(Integer modifiedBy) {
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * ID of a user
   * @return modifiedBy
  **/
  @ApiModelProperty(required = true, value = "ID of a user")
  public Integer getModifiedBy() {
    return modifiedBy;
  }

  public void setModifiedBy(Integer modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public Comment deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public Comment status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(required = true, value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Comment body(CommentBody body) {
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @ApiModelProperty(required = true, value = "")
  public CommentBody getBody() {
    return body;
  }

  public void setBody(CommentBody body) {
    this.body = body;
  }

  public Comment commentType(CommentTypeEnum commentType) {
    this.commentType = commentType;
    return this;
  }

   /**
   * Get commentType
   * @return commentType
  **/
  @ApiModelProperty(required = true, value = "")
  public CommentTypeEnum getCommentType() {
    return commentType;
  }

  public void setCommentType(CommentTypeEnum commentType) {
    this.commentType = commentType;
  }

  public Comment location(CommentLocation location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(required = true, value = "")
  public CommentLocation getLocation() {
    return location;
  }

  public void setLocation(CommentLocation location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Comment comment = (Comment) o;
    return Objects.equals(this.id, comment.id) &&
        Objects.equals(this.inReplyTo, comment.inReplyTo) &&
        Objects.equals(this.createdDate, comment.createdDate) &&
        Objects.equals(this.createdBy, comment.createdBy) &&
        Objects.equals(this.modifiedBy, comment.modifiedBy) &&
        Objects.equals(this.deleted, comment.deleted) &&
        Objects.equals(this.status, comment.status) &&
        Objects.equals(this.body, comment.body) &&
        Objects.equals(this.commentType, comment.commentType) &&
        Objects.equals(this.location, comment.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, inReplyTo, createdDate, createdBy, modifiedBy, deleted, status, body, commentType, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Comment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inReplyTo: ").append(toIndentedString(inReplyTo)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    commentType: ").append(toIndentedString(commentType)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

