/*
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.PageInfo;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * CreatedResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-07T18:50:05.195+01:00")
public class CreatedResponse {
  @SerializedName("status")
  private Integer status = null;

  @SerializedName("statusReasonPhrase")
  private String statusReasonPhrase = null;

  @SerializedName("pageInfo")
  private PageInfo pageInfo = null;

  @SerializedName("headers")
  private Map<String, List<String>> headers = null;

  @SerializedName("location")
  private String location = null;

  public CreatedResponse status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public CreatedResponse statusReasonPhrase(String statusReasonPhrase) {
    this.statusReasonPhrase = statusReasonPhrase;
    return this;
  }

   /**
   * Get statusReasonPhrase
   * @return statusReasonPhrase
  **/
  @ApiModelProperty(value = "")
  public String getStatusReasonPhrase() {
    return statusReasonPhrase;
  }

  public void setStatusReasonPhrase(String statusReasonPhrase) {
    this.statusReasonPhrase = statusReasonPhrase;
  }

  public CreatedResponse pageInfo(PageInfo pageInfo) {
    this.pageInfo = pageInfo;
    return this;
  }

   /**
   * Get pageInfo
   * @return pageInfo
  **/
  @ApiModelProperty(value = "")
  public PageInfo getPageInfo() {
    return pageInfo;
  }

  public void setPageInfo(PageInfo pageInfo) {
    this.pageInfo = pageInfo;
  }

  public CreatedResponse headers(Map<String, List<String>> headers) {
    this.headers = headers;
    return this;
  }

  public CreatedResponse putHeadersItem(String key, List<String> headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<String, List<String>>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @ApiModelProperty(value = "")
  public Map<String, List<String>> getHeaders() {
    return headers;
  }

  public void setHeaders(Map<String, List<String>> headers) {
    this.headers = headers;
  }

  public CreatedResponse location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @ApiModelProperty(value = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatedResponse createdResponse = (CreatedResponse) o;
    return Objects.equals(this.status, createdResponse.status) &&
        Objects.equals(this.statusReasonPhrase, createdResponse.statusReasonPhrase) &&
        Objects.equals(this.pageInfo, createdResponse.pageInfo) &&
        Objects.equals(this.headers, createdResponse.headers) &&
        Objects.equals(this.location, createdResponse.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, statusReasonPhrase, pageInfo, headers, location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatedResponse {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusReasonPhrase: ").append(toIndentedString(statusReasonPhrase)).append("\n");
    sb.append("    pageInfo: ").append(toIndentedString(pageInfo)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

