/*
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FilterOrderRule;
import io.swagger.client.model.FilterRule;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * FilterQuery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-07T18:50:05.195+01:00")
public class FilterQuery {
  @SerializedName("name")
  private String name = null;

  @SerializedName("rule")
  private FilterRule rule = null;

  @SerializedName("orderRules")
  private List<FilterOrderRule> orderRules = new ArrayList<FilterOrderRule>();

  public FilterQuery name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FilterQuery rule(FilterRule rule) {
    this.rule = rule;
    return this;
  }

   /**
   * Get rule
   * @return rule
  **/
  @ApiModelProperty(required = true, value = "")
  public FilterRule getRule() {
    return rule;
  }

  public void setRule(FilterRule rule) {
    this.rule = rule;
  }

  public FilterQuery orderRules(List<FilterOrderRule> orderRules) {
    this.orderRules = orderRules;
    return this;
  }

  public FilterQuery addOrderRulesItem(FilterOrderRule orderRulesItem) {
    this.orderRules.add(orderRulesItem);
    return this;
  }

   /**
   * Get orderRules
   * @return orderRules
  **/
  @ApiModelProperty(required = true, value = "")
  public List<FilterOrderRule> getOrderRules() {
    return orderRules;
  }

  public void setOrderRules(List<FilterOrderRule> orderRules) {
    this.orderRules = orderRules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterQuery filterQuery = (FilterQuery) o;
    return Objects.equals(this.name, filterQuery.name) &&
        Objects.equals(this.rule, filterQuery.rule) &&
        Objects.equals(this.orderRules, filterQuery.orderRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, rule, orderRules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterQuery {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    rule: ").append(toIndentedString(rule)).append("\n");
    sb.append("    orderRules: ").append(toIndentedString(orderRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

