/*
 * Jama REST API
 * This is the documentation for the Jama REST API.
 *
 * OpenAPI spec version: latest
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.RelationshipTypeDataListWrapper;
import io.swagger.client.model.RelationshipTypeDataWrapper;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RelationshiptypesApi
 */
@Ignore
public class RelationshiptypesApiTest {

    private final RelationshiptypesApi api = new RelationshiptypesApi();

    
    /**
     * Get the relationship type with the specified ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRelationshipTypeTest() throws ApiException {
        Integer id = null;
        String timestamp = null;
        List<String> include = null;
        RelationshipTypeDataWrapper response = api.getRelationshipType(id, timestamp, include);

        // TODO: test validations
    }
    
    /**
     * Get all relationship types
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRelationshipTypesTest() throws ApiException {
        Integer startAt = null;
        Integer maxResults = null;
        List<String> include = null;
        RelationshipTypeDataListWrapper response = api.getRelationshipTypes(startAt, maxResults, include);

        // TODO: test validations
    }
    
}
